services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: polling_app_dev
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data