import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :esbuild,
  version: "0.17.11",
  default: [
    args:
      ~w(js/app.js --bundle --target=es2017 --outdir=../priv/static/assets --external:/fonts/* --external:/images/*),
    cd: Path.expand("../assets", __DIR__),
    env: %{"NODE_PATH" => Path.expand("../deps", __DIR__)}
  ]

config :task_manager, TaskManager.Repo,
  username: System.get_env("DB_USERNAME") || "postgres",
  password: System.get_env("DB_PASSWORD") || "postgres",
  hostname: System.get_env("DB_HOST") || "db",
  database: System.get_env("DB_NAME") || "task_manager_dev",
  port: String.to_integer(System.get_env("DB_PORT") || "5432"),
  pool_size: String.to_integer(System.get_env("DB_POOL_SIZE") || "15")

config :task_manager, TaskManagerWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

config :task_manager, TaskManagerWeb.Endpoint,
  http: [port: String.to_integer(System.get_env("PORT") || "4000")],
  # Using 443 for HTTPS
  url: [host: "task-manager-ostin.fly.dev", port: 443],
  check_origin: [
    "https://task-manager-ostin.fly.dev",
    "http://localhost:4000",
    "http://127.0.0.1:4000"
  ],
  secret_key_base:
    System.get_env("SECRET_KEY_BASE") || "tJshweRt24XKAMWML94++xpBMWk5ALR2YIjOjFcyoQbElL4LQXKJrUvawh6ug10+",
  code_reloader: false,
  debug_errors: false,
  # No watchers in production
  watchers: []

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: TaskManager.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
